server:
  port: 8024
  context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: hysw-cost
  thymeleaf:
    # prefix : classpath:/templates/
    # suffix : .html
    mode: LEGACYHTML5
    cache: false
  jpa:
    generate-ddl: false
    show-sql: true
    # properties.hibernate.format_sql: true
    # properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
mybatis:
  type-aliases-package: net.tec.cloud.**.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
  mappers:
    - net.tec.cloud.common.dao.BaseMapper
  not-empty: false
  identity: MYSQL
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.cloud.sleuth: DEBUG
    # org.springframework.web.servlet.DispatcherServlet: DEBUG
app:
  #  华衍测试环境地址
  attachPath: /data/images
#  attachPath: /app/data
  testPath: D://upload
user_account: test1
verification_flag: 0
